const DD="https://www.doordash.com/store/irma%27s-flowers-sacramento-24536205/",WA="19165413044",STEP=18;
let category="All",query="",visible=STEP,language="en";
const cards=[...document.querySelectorAll(".product-card")];
const categoryNames=["All","Most Ordered","Fresh Blooms","Fresh Flowers","Sympathy","Lux Flowers","Plush Bears","Balloon","Chocolates"];
const copy={
  en:{heroTitle:"Fresh flowers for every moment",heroText:"Floral arrangements prepared with love, attention, and a truly special touch.",heroButton:"View arrangements",catalogEyebrow:"Our catalog",catalogTitle:"Find the perfect arrangement",catalogNote:"Select a photo for DoorDash delivery, or use WhatsApp to order for store pickup.",search:"Search arrangements...",products:"products",photo:"Order on DoorDash",doordash:"DoorDash delivery",whatsapp:"WhatsApp · Pickup",emptyTitle:"We couldn't find that arrangement",emptyText:"Try another name or choose a different category.",more:"View more arrangements",pickupEyebrow:"Prefer pickup?",pickupTitle:"Order on WhatsApp and pick up in store",pickupText:"We will confirm availability, pickup time, and total before preparing your order.",pickupButton:"Message us on WhatsApp",footer:"Flowers to celebrate, comfort, and remember.",language:"Español",languageLabel:"Ver en español"},
  es:{heroTitle:"Flores frescas para cada momento",heroText:"Arreglos florales preparados con amor, atención y un toque verdaderamente especial.",heroButton:"Ver arreglos",catalogEyebrow:"Nuestro catálogo",catalogTitle:"Encuentra el arreglo perfecto",catalogNote:"Presiona la fotografía para ordenar entrega en DoorDash, o usa WhatsApp para recoger en tienda.",search:"Buscar arreglos...",products:"productos",photo:"Ordenar en DoorDash",doordash:"Entrega por DoorDash",whatsapp:"WhatsApp · Recoger",emptyTitle:"No encontramos ese arreglo",emptyText:"Prueba otro nombre o selecciona una categoría diferente.",more:"Ver más arreglos",pickupEyebrow:"¿Prefieres recoger?",pickupTitle:"Ordena por WhatsApp y recoge en la tienda",pickupText:"Te confirmaremos disponibilidad, horario y total antes de preparar tu pedido.",pickupButton:"Escribir por WhatsApp",footer:"Flores para celebrar, acompañar y recordar.",language:"English",languageLabel:"View in English"}
};
const labels={
  en:{All:"All","Most Ordered":"Most Ordered","Fresh Blooms":"Fresh Blooms","Fresh Flowers":"Fresh Flowers",Sympathy:"Sympathy","Lux Flowers":"Lux Flowers","Plush Bears":"Plush Bears",Balloon:"Balloons",Chocolates:"Chocolates"},
  es:{All:"Todos","Most Ordered":"Más pedidos","Fresh Blooms":"Flores frescas","Fresh Flowers":"Arreglos florales",Sympathy:"Condolencias","Lux Flowers":"Flores de lujo","Plush Bears":"Osos de peluche",Balloon:"Globos",Chocolates:"Chocolates"}
};
const count=document.querySelector("#count"),more=document.querySelector("#more"),empty=document.querySelector("#empty");
function matches(card){const categoryMatch=category==="All"||card.dataset.category===category;const term=query.trim().toLowerCase();return categoryMatch&&(!term||card.dataset.name.includes(term)||card.dataset.description.includes(term))}
function whatsapp(card){const name=card.dataset.product,price=card.dataset.price;const lines=language==="en"?["Hello, I would like to order for store pickup:","",`Product: ${name}`,`Price: $${price}`,"","My name:","Pickup date and time:","Card message:","Occasion:","","Could you please confirm availability and the total?"]:["Hola, quiero ordenar para recoger en la tienda:","",`Producto: ${name}`,`Precio: $${price}`,"","Mi nombre:","Fecha y hora para recoger:","Mensaje para la tarjeta:","Ocasión:","","¿Podrían confirmarme la disponibilidad y el total, por favor?"];return `https://wa.me/${WA}?text=${encodeURIComponent(lines.join("\n"))}`}
function render(){const t=copy[language],filtered=cards.filter(matches);cards.forEach(card=>card.hidden=true);filtered.slice(0,visible).forEach(card=>card.hidden=false);count.textContent=`${filtered.length} ${t.products}`;empty.hidden=filtered.length>0;more.hidden=visible>=filtered.length;cards.forEach(card=>{card.querySelector(".image-action").textContent=t.photo;card.querySelector(".button.doordash").textContent=t.doordash;const wa=card.querySelector(".button.whatsapp");wa.textContent=t.whatsapp;wa.href=whatsapp(card);card.querySelector(".product-category").textContent=labels[language][card.dataset.category]||card.dataset.category})}
function categories(){document.querySelector("#categories").innerHTML=categoryNames.map(item=>`<button class="category ${item===category?"active":""}" data-cat="${item}">${labels[language][item]}</button>`).join("");document.querySelectorAll("[data-cat]").forEach(button=>button.onclick=()=>{category=button.dataset.cat;visible=STEP;categories();render()})}
function translate(){const t=copy[language];document.documentElement.lang=language;document.querySelector("#hero-title").textContent=t.heroTitle;document.querySelector("#hero-text").textContent=t.heroText;document.querySelector("#hero-button").textContent=t.heroButton;document.querySelector("#catalog-eyebrow").textContent=t.catalogEyebrow;document.querySelector("#catalog-title").textContent=t.catalogTitle;document.querySelector("#catalog-note").textContent=t.catalogNote;document.querySelector("#search").placeholder=t.search;document.querySelector("#empty-title").textContent=t.emptyTitle;document.querySelector("#empty-text").textContent=t.emptyText;more.textContent=t.more;document.querySelector("#pickup-eyebrow").textContent=t.pickupEyebrow;document.querySelector("#pickup-title").textContent=t.pickupTitle;document.querySelector("#pickup-text").textContent=t.pickupText;const pickup=document.querySelector("#pickup-button");pickup.textContent=t.pickupButton;pickup.href=`https://wa.me/${WA}?text=${encodeURIComponent(language==="en"?"Hello, I would like to order a floral arrangement for store pickup.":"Hola, quiero ordenar un arreglo floral para recoger en la tienda.")}`;document.querySelector("#footer-text").textContent=t.footer;const lang=document.querySelector("#language");lang.textContent=t.language;lang.setAttribute("aria-label",t.languageLabel);categories();render()}
document.querySelector("#search").oninput=event=>{query=event.target.value;visible=STEP;render()};
more.onclick=()=>{visible+=STEP;render()};
document.querySelector("#language").onclick=()=>{language=language==="en"?"es":"en";translate()};
translate();
