const DD="https://www.doordash.com/store/irma%27s-flowers-sacramento-24536205/",WA="19165413044",STEP=10;
let category="All",query="",visible=STEP,language="en";
const cards=[...document.querySelectorAll(".product-card")];
const categoryNames=["All","Most Ordered","Fresh Blooms","Fresh Flowers","Sympathy","Lux Flowers","Plush Bears","Balloon","Chocolates"];
const copy={
  en:{heroTitle:"Fresh flowers for every moment",heroText:"Floral arrangements prepared with love, attention, and a truly special touch.",heroButton:"View arrangements",catalogEyebrow:"Our catalog",catalogTitle:"Find the perfect arrangement",catalogNote:"Select a photo for DoorDash delivery, or use WhatsApp to order for store pickup.",search:"Search by color, flower, or name...",products:"products",photo:"Order on DoorDash",doordash:"DoorDash delivery",whatsapp:"WhatsApp · Pickup",emptyTitle:"We couldn't find that arrangement",emptyText:"Try another color, flower, name, or category.",more:"View 10 more arrangements",pickupEyebrow:"Prefer pickup?",pickupTitle:"Order on WhatsApp and pick up in store",pickupText:"We will confirm availability, pickup time, and total before preparing your order.",pickupButton:"Message us on WhatsApp",footer:"Flowers to celebrate, comfort, and remember.",language:"Español",languageLabel:"Ver en español",top:"Back to top"},
  es:{heroTitle:"Flores frescas para cada momento",heroText:"Arreglos florales preparados con amor, atención y un toque verdaderamente especial.",heroButton:"Ver arreglos",catalogEyebrow:"Nuestro catálogo",catalogTitle:"Encuentra el arreglo perfecto",catalogNote:"Presiona la fotografía para ordenar entrega en DoorDash, o usa WhatsApp para recoger en tienda.",search:"Busca por color, flor o nombre...",products:"productos",photo:"Ordenar en DoorDash",doordash:"Entrega por DoorDash",whatsapp:"WhatsApp · Recoger",emptyTitle:"No encontramos ese arreglo",emptyText:"Prueba otro color, flor, nombre o categoría.",more:"Ver 10 arreglos más",pickupEyebrow:"¿Prefieres recoger?",pickupTitle:"Ordena por WhatsApp y recoge en la tienda",pickupText:"Te confirmaremos disponibilidad, horario y total antes de preparar tu pedido.",pickupButton:"Escribir por WhatsApp",footer:"Flores para celebrar, acompañar y recordar.",language:"English",languageLabel:"View in English",top:"Volver arriba"}
};
const labels={
  en:{All:"All","Most Ordered":"Most Ordered","Fresh Blooms":"Fresh Blooms","Fresh Flowers":"Fresh Flowers",Sympathy:"Sympathy","Lux Flowers":"Lux Flowers","Plush Bears":"Plush Bears",Balloon:"Balloons",Chocolates:"Chocolates"},
  es:{All:"Todos","Most Ordered":"Más pedidos","Fresh Blooms":"Flores frescas","Fresh Flowers":"Arreglos florales",Sympathy:"Condolencias","Lux Flowers":"Flores de lujo","Plush Bears":"Osos de peluche",Balloon:"Globos",Chocolates:"Chocolates"}
};
const count=document.querySelector("#count"),more=document.querySelector("#more"),empty=document.querySelector("#empty"),categoriesNav=document.querySelector("#categories"),backToTop=document.querySelector("#back-to-top");
const normalize=value=>value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");
const synonymGroups=[
  ["yellow","amarillo","amarilla","amarillos","amarillas","gold","golden","dorado","dorada"],
  ["red","rojo","roja","rojos","rojas"],["blue","azul","azules"],["white","blanco","blanca","blancos","blancas"],
  ["pink","rosa","rosado","rosada"],["orange","naranja","anaranjado","anaranjada"],["purple","morado","morada","violet","violeta"],
  ["black","negro","negra"],["green","verde","verdes"],["cream","crema"],["lavender","lavanda"],
  ["peach","durazno","duraznos"],["burgundy","wine","vino"],["brown","cafe","marron"],
  ["colorful","multicolor","colores","colorido","colorida"],["pastel","pastels","pasteles"],
  ["rose","roses","rosas","rosal"],["tulip","tulips","tulipan","tulipanes"],["carnation","carnations","clavel","claveles"],
  ["sunflower","sunflowers","girasol","girasoles"],["lily","lilies","lirio","lirios","azucena","azucenas"],
  ["orchid","orchids","orquidea","orquideas"],["daisy","daisies","margarita","margaritas"],["pom","poms","pompom","pompon","pompones"],
  ["flower","flowers","flor","flores","bloom","blooms"],["bouquet","bouquets","ramo","ramos","arreglo","arreglos"],
  ["baby's breath","babys breath","gypsophila","nube","velo de novia"]
].map(group=>group.map(normalize));
function searchGroups(value){return normalize(value).split(/\s+/).filter(Boolean).map(token=>synonymGroups.find(group=>group.includes(token))||[token])}
function matches(card){const categoryMatch=category==="All"||card.dataset.category===category;if(!categoryMatch)return false;const groups=searchGroups(query);if(groups.length===0)return true;const haystack=normalize(`${card.dataset.name} ${card.dataset.description} ${card.dataset.category}`);return groups.every(group=>group.some(term=>haystack.includes(term)))}
function whatsapp(card){const name=card.dataset.product,price=card.dataset.price;const lines=language==="en"?["Hello, I would like to order for store pickup:","",`Product: ${name}`,`Price: $${price}`,"","My name:","Pickup date and time:","Card message:","Occasion:","","Could you please confirm availability and the total?"]:["Hola, quiero ordenar para recoger en la tienda:","",`Producto: ${name}`,`Precio: $${price}`,"","Mi nombre:","Fecha y hora para recoger:","Mensaje para la tarjeta:","Ocasión:","","¿Podrían confirmarme la disponibilidad y el total, por favor?"];return `https://wa.me/${WA}?text=${encodeURIComponent(lines.join("\n"))}`}
function render(){const t=copy[language],filtered=cards.filter(matches);cards.forEach(card=>card.hidden=true);filtered.slice(0,visible).forEach(card=>card.hidden=false);count.textContent=`${filtered.length} ${t.products}`;empty.hidden=filtered.length>0;more.hidden=visible>=filtered.length;cards.forEach(card=>{card.querySelector(".image-action").textContent=t.photo;card.querySelector(".button.doordash").textContent=t.doordash;const wa=card.querySelector(".button.whatsapp");wa.textContent=t.whatsapp;wa.href=whatsapp(card);card.querySelector(".product-category").textContent=labels[language][card.dataset.category]||card.dataset.category})}
function categories(){categoriesNav.innerHTML=categoryNames.map(item=>`<button class="category ${item===category?"active":""}" type="button" data-cat="${item}" aria-pressed="${item===category}">${labels[language][item]}</button>`).join("")}
function translate(){const t=copy[language];document.documentElement.lang=language;document.querySelector("#hero-title").textContent=t.heroTitle;document.querySelector("#hero-text").textContent=t.heroText;document.querySelector("#hero-button").textContent=t.heroButton;document.querySelector("#catalog-eyebrow").textContent=t.catalogEyebrow;document.querySelector("#catalog-title").textContent=t.catalogTitle;document.querySelector("#catalog-note").textContent=t.catalogNote;document.querySelector("#search").placeholder=t.search;document.querySelector("#empty-title").textContent=t.emptyTitle;document.querySelector("#empty-text").textContent=t.emptyText;more.textContent=t.more;document.querySelector("#pickup-eyebrow").textContent=t.pickupEyebrow;document.querySelector("#pickup-title").textContent=t.pickupTitle;document.querySelector("#pickup-text").textContent=t.pickupText;const pickup=document.querySelector("#pickup-button");pickup.textContent=t.pickupButton;pickup.href=`https://wa.me/${WA}?text=${encodeURIComponent(language==="en"?"Hello, I would like to order a floral arrangement for store pickup.":"Hola, quiero ordenar un arreglo floral para recoger en la tienda.")}`;document.querySelector("#footer-text").textContent=t.footer;const lang=document.querySelector("#language");lang.textContent=t.language;lang.setAttribute("aria-label",t.languageLabel);backToTop.setAttribute("aria-label",t.top);backToTop.title=t.top;categories();render()}
document.querySelector("#search").oninput=event=>{query=event.target.value;visible=STEP;render()};
more.onclick=()=>{visible+=STEP;render()};
categoriesNav.addEventListener("click",event=>{const button=event.target.closest("[data-cat]");if(!button)return;category=button.dataset.cat;visible=STEP;categories();render();document.querySelector("#catalogo").scrollIntoView({behavior:"smooth",block:"start"})});
document.querySelector("#language").onclick=()=>{language=language==="en"?"es":"en";translate()};
window.addEventListener("scroll",()=>backToTop.classList.toggle("visible",window.scrollY>600),{passive:true});
translate();
